[package]
name = "wasmedge-tf-wasmedge-image"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasmedge_tensorflow_interface = "^0.2.2"
